# Configuration file for SignMap plugin
# Made by Alskar with <3

# Shows cute kitten looking at you in console when plugin is enabled.
# Set it to false in case you're a dog person.
enable-kitten-on-startup: true

# Should the prefix with plugin name be shown before in-game messages?
# This setting doesn't affect messages in the console.
show-prefix: true