name: SignIt
main: ru.alskar.signit.SignIt
version: ${project.version}
author: "Alskar"
api-version: "1.14"
permissions:
  signit.sign:
    description: "Players with this permission are able to sign maps"
    default: true
  signit.unsign:
    description: "Players with this permission are able to unsign maps signed by them"
    default: true
  signit.signall:
    description: "Players with this permission are able to sign all maps in their inventory"
    default: true
  signit.unsignall:
    description: "Players with this permission are able to unsign all allowed maps in their inventory"
    default: true
  signit.unsign.others:
    description: "Players with this permission are able to unsign maps signed by other players. Server operators have this by default"
    default: op
  signit.reload:
    description: "Players with this permission are able to reload plugin configuration and active language file"
    default: op
commands:
  signit:
    description: "Sings map in main hand, preventing others from copying it."
    usage: /<command>
  unsignit:
    description: "Unsigns map in main hand, so anyone can copy it. Available only for player who signed the map and operators"
    usage: /<command>
  signall:
    description: "Sings all accessible maps in player's inventory"
    usage: /<command>
  unsignall:
    description: "Unsigns all accessible maps in player's inventory"
    usage: /<command>
  reload:
    description: "Reloads plugin configuration and language file specified in config"
    usage: /<command>